# version: "3.9"

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 1234560123
      TZ: "Asia/Ho_Chi_Minh"
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
  
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      MSSQL_SA_PASSWORD: "SAJx123456"
      ACCEPT_EULA: "Y"
      TZ: "Asia/Ho_Chi_Minh"
    ports:
      - 1433:1433
    volumes:
      - mssql_data:/var/opt/mssql
  
  # goddess:
  #   depends_on:
  #     - mysql
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   volumes:
  #     - server_data:/server
  #   ports:
  #     - 5001:5001

volumes:
  mysql_data:
  mssql_data:
  server_data: